[package]
name = "stormi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.5.0"
infer = "0.3"
glob = "0.3.0"
rand = "0.8.4"
sha2 = "0.9.8"
hmac = "0.11.0"
tower = "0.4.10"
serde_yaml = "0.8"
futures = "0.3.17"
axum-debug = "0.1.0"
async-trait = "0.1.51"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14.14", features = ["full"] }
axum = { version = "0.3.0", features = ["multipart"] }
tower-http = { version = "0.1.1", features = ["full"] }
