[package]
name = "stormi"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
rand = "0.8.4"
infer = "0.5.0"
tower = "0.4.11"
base64 = "0.13.0"
futures = "0.3.19"
axum-debug = "0.3.2"
serde_yaml = "0.8.23"
async-trait = "0.1.52"
tokio = { version = "1.15.0", features = ["full"] }
hyper = { version = "0.14.16", features = ["full"] }
serde = { version = "1.0.132", features = ["derive"] }
axum = { version = "0.4.3", features = ["multipart"] }
tower-http = { version = "0.2.0", features = ["full"] }
