[package]
name = "stormi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
rand = "0.8.4"
infer = "0.5.0"
tower = "0.4.11"
base64 = "0.13.0"
futures = "0.3.18"
axum-debug = "0.3.0"
serde_yaml = "0.8.21"
async-trait = "0.1.51"
tokio = { version = "1.14.0", features = ["full"] }
hyper = { version = "0.14.15", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
axum = { version = "0.4.0", features = ["multipart"] }
tower-http = { version = "0.2.0", features = ["full"] }
