[package]
name = "stormi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
infer = "0.3"
glob = "0.3.0"
rand = "0.8.4"
ring = "0.16.20"
tower = "0.4.10"
axum-debug = "0.1.0"
simplelog = "0.10.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14.14", features = ["full"] }
axum = { version = "0.2.8", features = ["multipart"] }
